DROP DATABASE IF EXISTS PROYECTO_INTEGRADOR;
CREATE DATABASE PROYECTO_INTEGRADOR;
USE PROYECTO_INTEGRADOR;

CREATE TABLE CLIENTE(
CEDULA INT NOT NULL, 
NOMBRE VARCHAR (57) NOT NULL, 
APELLIDOS VARCHAR (57) NOT NULL,
CELULAR INT NOT NULL, 
CORREOE VARCHAR (57) NOT NULL, 
DIRECCION VARCHAR (57) NOT NULL, 
CIUDAD VARCHAR (57) NOT NULL
);
 
CREATE TABLE EMPLEADO (
CEDULA INT NOT NULL,
NOMBRE VARCHAR (57)NOT NULL, 
APELLIDO VARCHAR (57) NOT NULL, 
CELULAR INT (11)NOT NULL, 
CORREO VARCHAR (57) NOT NULL, 
DIRECCION VARCHAR (57)NOT NULL, 
CIUDAD VARCHAR (57) NOT NULL, 
ANTIGUEDAD INT  NOT NULL, 
RH VARCHAR (57)NOT NULL, 
TIPOEMPLEADO VARCHAR(3)
);
CREATE TABLE PAQUETE (
ID INT NOT NULL, 
TIPO VARCHAR (57) NOT NULL, 
PESO INT NOT NULL, 
VALOR int
);
CREATE TABLE ENVIO (
NUMERO_GUIA VARCHAR (10),
CLIENTE VARCHAR(10),
 CIUDAD_ORIGEN VARCHAR (57),
 CIUDAD_DESTINO VARCHAR (57),
 DIRECCION_DESTINO VARCHAR (57), 
 NOMBRE_RECIBE VARCHAR (57), 
 CELULAR_RECIBE INT (15),
 HORA_ENTREGA VARCHAR (5), 
 ESTADO_ENVIO VARCHAR (57),
 VALOR_ENVIO INT (20)
 );

 


INSERT INTO EMPLEADOS VALUES ('12345','Mateo','Zapata','3046303886','mateo@gmail.com', 'calle 46 # 69-90','Medellin','1','O+','Repartidor') 